### ISSUE TITLE
input overlay not working in specific game window

### ISSUE THREAD

**Issue by yanodll** [univrsal/input-overlay#416] opened 2024-09-16 12:29 UTC
I'm using ver 5.0.5. Generally it's working fine in CS2 etc, but not in GRID 2. Can i do something about it?

**Comment by univrsal** [comment] 2024-09-16 15:45
I don't know what the issue is but it's probably the same bug as #415 so I'll close this as a duplicate

**Closed by univrsal** 2024-09-16 15:45 UTC
