### ISSUE TITLE
linux 5.0.0 odd mouse behavoir

### ISSUE THREAD

**Issue by t0ngub1n** [univrsal/input-overlay#235] opened 2022-03-10 17:51 UTC
on linux (ubuntu 20.04) when i click RMB it displays like wheel button. when i click wheel button it displays like an RMB click.

to reproduce: install 5.0.0 prerelease, default mouse preset.

if it depends on os, plz make separate presets for linux and windows. else plz fix presets.

plugin version: 5.0.0 prerelease.

**Comment by univrsal** [comment] 2022-03-10 21:38
duplicate of #180

**Closed by univrsal** 2022-03-10 21:38 UTC
