### ISSUE TITLE
Scroll Wheel input remains highlighted until other inputs are made (keyboard/mouse movement/clicking). Related issue: #134.

### ISSUE THREAD

**Issue by Jeanfeels** [univrsal/input-overlay#156] opened 2021-02-19 04:02 UTC
**Describe the bug**
When using any mouse overlay with scroll wheel, scrolling any number of notches without touching anything else will light the scroll direction on the overlay, as intended. However, this input display does not automatically time out (possibly a quirk of how scrollwheels work) and thus once you stop scrolling the icon remains lit until some other input occurs, such as clicking, moving the mouse, or typing. 

This is related to #134 and is the likely _cause_ for that issue existing.

**To Reproduce**
1. Begin with a mouse overlay set up.
2. Scroll down or up while keeping the mouse from moving.
3. Observe the scroll input remains lit even once scrolling has ceased.
4. Press any key or move the mouse or click, and observe that the moment you do, the input disappears.

**Expected behavior**
The scroll input indicator should properly display individual notches/lines of scroll input, without losing responsiveness, and without remaining lit constantly until other inputs are pressed.

A more effective and scalable method of displaying scroll inputs, such as a short, transparent outward ripple animation that can stack a few times, could solve this issue, or having the hue of the scroll indicator shift with every scroll input, or any number of other solutions along those lines. 

For examples of what I mean: 
https://i.stack.imgur.com/VzMFx.gif
https://cdn.dribbble.com/users/1112522/screenshots/5398201/wave-effect.gif

**Additional information:**
- Latest plugin release as of writing.
- OBS log:
```
11:17:22.964: CoInitializeEx succeeded: 0x00000001
11:17:22.964: CPU Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
11:17:22.964: CPU Speed: 2208MHz
11:17:22.964: Physical Cores: 6, Logical Cores: 12
11:17:22.964: Physical Memory: 16284MB Total, 4046MB Free
11:17:22.964: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1316; 64-bit)
11:17:22.964: Running as administrator: false
11:17:22.964: Aero is Enabled (Aero is always on for windows 8 and above)
11:17:22.964: Windows 10 Gaming Features:
11:17:22.965: 	Game Bar: On
11:17:22.965: 	Game DVR: On
11:17:22.965: 	Game DVR Background Recording: Off
11:17:22.965: 	Game Mode: Off
11:17:22.967: Sec. Software Status:
11:17:22.969: 	Windows Defender Antivirus: disabled (AV)
11:17:22.969: 	Bitdefender Antivirus Free Antimalware: enabled (AV)
11:17:22.969: 	Windows Firewall: enabled (FW)
11:17:22.970: Current Date/Time: 2021-02-19, 11:17:22
11:17:22.970: Browser Hardware Acceleration: true
11:17:22.970: Portable mode: false
11:17:23.453: OBS 25.0.1 (64-bit, windows)
11:17:23.453: ---------------------------------
11:17:23.454: ---------------------------------
11:17:23.454: audio settings reset:
11:17:23.454: 	samples per sec: 44100
11:17:23.454: 	speakers:        2
11:17:23.456: ---------------------------------
11:17:23.456: Initializing D3D11...
11:17:23.456: Available Video Adapters: 
11:17:23.461: 	Adapter 0: Intel(R) UHD Graphics 630
11:17:23.461: 	  Dedicated VRAM: 134217728
11:17:23.462: 	  Shared VRAM:    4242593792
11:17:23.462: 	  Driver Version: 26.20.100.7261
11:17:23.463: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=144, name=
11:17:23.463: 	Adapter 1: NVIDIA GeForce GTX 1070 with Max-Q Design
11:17:23.463: 	  Dedicated VRAM: 4179623936
11:17:23.463: 	  Shared VRAM:    4242593792
11:17:23.464: 	  Driver Version: 26.21.14.4575
11:17:23.464: 	  output 0: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=60, name=SA300/SA350
11:17:23.468: Loading up D3D11 on adapter Intel(R) UHD Graphics 630 (0)
11:17:23.517: D3D11 loaded successfully, feature level used: b000
11:17:23.517: DXGI increase maximum frame latency success
11:17:24.256: ---------------------------------
11:17:24.256: video settings reset:
11:17:24.256: 	base resolution:   1920x1080
11:17:24.256: 	output resolution: 1920x1080
11:17:24.256: 	downscale filter:  Lanczos
11:17:24.256: 	fps:               60/1
11:17:24.256: 	format:            NV12
11:17:24.256: 	YUV mode:          601/Partial
11:17:24.256: NV12 texture support not available
11:17:24.257: Audio monitoring device:
11:17:24.257: 	name: CABLE Input (VB-Audio Virtual Cable)
11:17:24.257: 	id: {0.0.0.00000000}.{c7bc928f-4cba-4bce-a550-9943da9059eb}
11:17:24.257: ---------------------------------
11:17:24.261: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
11:17:24.263: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
11:17:24.314: [AMF] Unable to load 'amfrt64.dll', error code 126.
11:17:24.318: [AMF] AMF Test failed due to one or more errors.
11:17:24.318: Failed to initialize module 'enc-amf.dll'
11:17:24.351: [obs-browser]: Version 2.8.6
11:17:24.352: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
11:17:24.358: NVENC supported
11:17:24.395: Couldn't find VLC installation, VLC video source disabled
11:17:24.407: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
11:17:24.409: No blackmagic support
11:17:24.415: ---------------------------------
11:17:24.415:   Loaded Modules:
11:17:24.415:     win-wasapi.dll
11:17:24.415:     win-mf.dll
11:17:24.415:     win-dshow.dll
11:17:24.416:     win-decklink.dll
11:17:24.416:     win-capture.dll
11:17:24.416:     vlc-video.dll
11:17:24.416:     text-freetype2.dll
11:17:24.416:     rtmp-services.dll
11:17:24.416:     obs-x264.dll
11:17:24.416:     obs-vst.dll
11:17:24.416:     obs-virtualoutput.dll
11:17:24.416:     obs-transitions.dll
11:17:24.416:     obs-text.dll
11:17:24.416:     obs-qsv11.dll
11:17:24.416:     obs-outputs.dll
11:17:24.416:     obs-filters.dll
11:17:24.416:     obs-ffmpeg.dll
11:17:24.416:     obs-browser.dll
11:17:24.416:     input-overlay.dll
11:17:24.416:     image-source.dll
11:17:24.416:     frontend-tools.dll
11:17:24.416:     enc-amf.dll
11:17:24.416:     decklink-ouput-ui.dll
11:17:24.416:     coreaudio-encoder.dll
11:17:24.416: ---------------------------------
11:17:24.416: ==== Startup complete ===============================================
11:17:24.424: All scene data cleared
11:17:24.424: ------------------------------------------------
11:17:24.472: WASAPI: Device 'Speakers (Yeti Stereo Microphone)' [48000 Hz] initialized
11:17:24.604: WASAPI: Device 'Microphone (Yeti Stereo Microphone)' [44100 Hz] initialized
11:17:24.645: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
11:17:24.645: 
11:17:25.630: Switched to scene 'Loco'
11:17:25.633: ------------------------------------------------
11:17:25.633: Loaded scenes:
11:17:25.633: - scene 'Loco':
11:17:25.694:     - source: 'Display Capture' (monitor_capture)
11:17:25.694:     - source: 'Input Overlay' (input-overlay)
11:17:25.694:     - source: 'Input Overlay 2' (input-overlay)
11:17:25.694: - scene 'Scene 3':
11:17:25.694:     - source: 'Game Capture 3' (game_capture)
11:17:25.694: - scene 'Scene':
11:17:25.694:     - source: 'Astroneer' (game_capture)
11:17:25.694:     - source: 'Game Capture' (game_capture)
11:17:25.694:     - source: 'Video Capture Device' (dshow_input)
11:17:25.694: - scene 'Scene 2':
11:17:25.694:     - source: 'Game Capture 2' (game_capture)
11:17:25.694:     - source: 'Video Capture Device 2' (dshow_input)
11:17:25.694: - scene 'Scene 4':
11:17:25.694:     - source: 'Game Capture 4' (game_capture)
11:17:25.694:     - source: 'Video Capture Device 3' (dshow_input)
11:17:25.694: - scene 'Satis':
11:17:25.694:     - source: 'Game Capture 5' (game_capture)
11:17:25.694: ------------------------------------------------
```

**Comment by univrsal** [comment] 2021-02-19 10:12
The problem is, that there is no event when scrolling stops, only when it starts, so there's no way to tell when scrolling stops. Currently if the next input is not a scroll wheel event it'll stop, the other solution is to check when the last scroll input happened and if it was too long ago it'll just assume that scrolling stopped. Neither of those solutions are perfect though

**Comment by univrsal** [comment] 2021-05-08 11:35
Fixed with the latest [pre-release](https://github.com/univrsal/input-overlay/releases)

**Closed by univrsal** 2021-05-08 11:35 UTC
