### ISSUE TITLE
V5 Doesn't recognize any key presses

### ISSUE THREAD

**Issue by BrunoGamerYT3** [univrsal/input-overlay#244] opened 2022-04-08 19:50 UTC
**Describe the bug**
None of the keys i press on my keyboard get recognized in v5

**To Reproduce**
Just set up the querty or any form of input as normal and it doesn't work for me

**Expected behavior**
Input overlay recognizing key presses

**Screenshots**

**Additional information:**
- Plugin version: 5.0.0rc1
- Full OBS Studio: https://pastebin.com/raw/5Cv9q1d8

**Additional context**
I tried everything from using a preset template and openning obs with admnistrator but nothing works
Also everything worked fine pre-5.0

**Comment by univrsal** [comment] 2022-12-06 20:05
Probably a duplicate of #160

**Closed by univrsal** 2022-12-06 20:05 UTC
