### ISSUE TITLE
Mouse Wheel dosen't work in OBS but in io-cct

### ISSUE THREAD

**Issue by xps1992** [univrsal/input-overlay#190] opened 2021-07-17 09:23 UTC
**Describe the bug**
Mouse Wheel dosen't work in OBS.

**To Reproduce**
If you test it in io-cct the wheel works finde but in OBS nothing happens.

Textrue and Config
[Keyinput-Overlay.zip](https://github.com/univrsal/input-overlay/files/6834516/Keyinput-Overlay.zip)

**Screenshots**
IO-CCT
![image](https://user-images.githubusercontent.com/16282126/126032163-79a6a624-cd65-4199-ae07-4c05e43a85cc.png)
OBS
![image](https://user-images.githubusercontent.com/16282126/126032193-0c394659-31d0-4132-9e2e-9ac9aef2c95c.png)
Plugin-Config
![image](https://user-images.githubusercontent.com/16282126/126032233-99dabe13-2a0a-41d1-ae07-926c013d132a.png)

**Additional information:**
- Plugin version: v5.0.0
- OBS verison: 27.0.1 (64 bit)
- Full OBS Studio log
[2021-07-17 11-10-02.txt](https://github.com/univrsal/input-overlay/files/6834509/2021-07-17.11-10-02.txt)

**Comment by univrsal** [comment] 2021-07-17 10:54
duplicate of #180

**Closed by univrsal** 2021-07-17 10:54 UTC
