### ISSUE TITLE
Arrow keys don't show they are being pressed.

### ISSUE THREAD

**Issue by Lyqed** [univrsal/input-overlay#346] opened 2023-05-27 14:05 UTC
*Describe the bug**
Arrow keys don't show they are being pressed.

**To Reproduce**
Map arrow keys accordingly.

**Expected behavior**
Arrow keys are shown to be pressed in the graphical interface.

**Screenshots and videos**
Image of bug:
![image](https://github.com/univrsal/input-overlay/assets/98341862/1d461f6a-f61e-4555-bb97-a68512bcc17a)

Video of bug:
https://github.com/univrsal/input-overlay/assets/98341862/3e01f78c-fdaa-4dc6-8693-20010f91d1d7

**Additional information:**
- Plugin version: 5.0.4
- Full OBS Studio log [here](https://obsproject.com/logs/gLQOKvVfI5oThHxy)

**Comment by univrsal** [comment] 2023-05-27 15:37
The codes for the arrow keys are wrong, try reassigning them with the config tool.

**Comment by Lyqed** [comment] 2023-05-27 18:44
> The codes for the arrow keys are wrong, try reassigning them with the config tool.

I have used the keycodes provided in uiohook. They are the correct keycodes for the arrow keys.

I even used the demo_hook.exe tool to double check.

**Comment by univrsal** [comment] 2023-05-27 20:12
Cannot reproduce, use the config tool.

https://github.com/univrsal/input-overlay/assets/8353672/16b786ee-2a83-4f64-b80d-2e7e30063bc8

**Closed by univrsal** 2023-05-27 20:12 UTC

**Comment by Lyqed** [comment] 2023-05-28 14:22
> Cannot reproduce, use the config tool.
> 
>  a.mp4

Would you be able to please share the json file of this? thanks (:
