### ISSUE TITLE
Inputs getting stuck/not showing

### ISSUE THREAD

**Issue by xoxfaby** [univrsal/input-overlay#357] opened 2023-07-15 16:54 UTC
**Describe the bug**
Inputs (I'm guessing both key up and key down events which sometimes gets the overlay stuck in a key being fake down) are being missed or something. 

**To Reproduce**
Add source, start pressing keys, after a few key presses a key won't light up or it will stay lit after it's released

**Expected behavior**
Keys are displayed accurately

**Screenshots**

**Additional information:**
- Tried both 5.0.3 and 5.0.4
- https://obsproject.com/logs/wDRAXERK8DW5WAWx

**Additional context**
I'm not sure if this is related but OBS also crashes because of input-overlay when I close it. Crashlog: https://gist.github.com/xoxfaby/278b7e84777b8a76fa9ef3ade7d10a84

**Comment by xoxfaby** [comment] 2023-07-15 17:26
Update: I figured out this issue occurs only when I have multiple instances of the "Audio Repeater (KS)" from [Virtual Audio Cable](https://vac.muzychenko.net/en/index.htm) running and active.

**Comment by univrsal** [comment] 2023-07-15 17:58
The crash seems unrelated. You have logi_obs_plugin_x64.dll installed (which apparently installs itself automatically). I think it's prone to causing issues so you might want to remove it unless you need it and see if that changes anything.

When I get time I'll try and install VAC to see if I can reproduce the issue.

**Comment by xoxfaby** [comment] 2023-07-15 18:01
I will note that it also doesn't appear to start happening until ~3 KS repeaters are active. Also, removing logi_obs_plugin_x64.dll made no difference

**Comment by xoxfaby** [comment] 2023-07-24 07:20
You should be able to recreate this with the lite version, it only allows one cable but multiple repeaters that just go from that cable back into it would hopefully recreate the same effect

**Comment by univrsal** [comment] 2023-07-24 10:24
I could reproduce the issue with the light version.

![image](https://github.com/univrsal/input-overlay/assets/8353672/90f6530d-eea2-45c9-80de-0687859d0681)

This also happens when using libuiohook examples, which means that this isn't a problem with input overlay. Maybe @Kwhat has an idea what's happening, but I feel like this might be an issue that VAC is causing. Might also be worth asking the developer of VAC.


I've attached the modified libuiohook demos I used for testing
[debug.zip](https://github.com/univrsal/input-overlay/files/12144717/debug.zip)

**Comment by xoxfaby** [comment] 2023-07-24 10:39
I'm guessing it is some sort of an issue with interrupts. I contacted the creator of VAC and this is all the info I got

> Please use Process Explorer and LatencyMon to check load distribution
and kernel latencies.

Unfortunately I don't think they're available to help with this atm.

**Comment by kwhat** [comment] 2023-07-24 23:53
> Maybe @kwhat has an idea what's happening

I am guessing you are asking why you are getting multiple key down events?  Maybe why you are getting multiple release events? The former is easier to explain than the latter.

What is VAC?

We probably want to check this with a custom build that uses the native sequential event id (instead of the epoch timestamp) to try and figure out what is happening here.

We probably also want full debug logs to try and understand what happened.  There are some really [messed up code ](https://github.com/kwhat/libuiohook/blob/1.3/src/windows/input_hook.c#L239C19-L239C19) around restarting the event hook under suspicious circumstances that cloud explain the latter missing events.

**Comment by kwhat** [comment] 2023-07-25 13:47
> Like in the output when each event is received?

I guess I called the structure element [time](https://github.com/kwhat/libuiohook/blob/1.3/src/windows/dispatch_event.c#L135).  Using the KBDLLHOOKSTRUCT->time is going to be slightly more accurate.  Some systems use a sequential number but unfortunate windows isnt that system.

The EVENT_OBJECT_NAMECHANGE stuff is in there because when some windows like RDP get focus, SetWindowsHookEx just stops working for no reason.  You can restart the hook and it just starts working again.  The only way I was able to try and detect when entering one of these windows EVENT_OBJECT_NAMECHANGE but it isn't the best answer.

**Comment by univrsal** [comment] 2023-07-25 21:15
I tried using the 1.3 branch both with and without USE_EPOCH_TIME and the problem persists. I feel like there's not much on libuiohook's side that can be done. Looking at LatencyMon I can see that apparently my system (which is a VM to be fair) is not capable of handling real time audio.
![image](https://github.com/univrsal/input-overlay/assets/8353672/1d810a17-4a97-439f-8f9f-585b58a48e83)
I assume that that might be why the events aren't delivered correctly anymore.
@xoxfaby have you run LatencyMon to see what the results are for you when running multiple instances of Audio Repeater?

**Comment by xoxfaby** [comment] 2023-07-25 21:19
LatencyMon said my system was fine for real-time audio. Even with 7 repeaters running. 

I would have to assume there is something that can be done if nothing else on the system is missing all these key events (or my whole system would be terribly unresponsive, right?) 

What @kwhat said made me think, about the lib rehooking, which made it seem plausible that events are being missed during this rehook, but that's a wild guess without knowing how any of this works.

**Comment by univrsal** [comment] 2023-07-25 21:34
Looks like you're right. The hook seems to restart a lot when I move my mouse, but for normal inputs it's fine. However when starting a VAC repeater it constantly restarts:

https://github.com/univrsal/input-overlay/assets/8353672/631afb66-c3ee-4bb1-a8ea-6fbb707737a4

**Comment by xoxfaby** [comment] 2023-07-25 21:38
Yeah that seems like it would be very problematic. I'm guessing we'll have to wait for @kwhat to weigh in on this?

Really hoping there is a solution for this because atm input overlay is completely unusable to me due to all of the missed events.

**Comment by univrsal** [comment] 2023-07-25 21:55
Well the solution for me seems to be to just not restart the hook. Now it seems to work fine. I'm not sure when restarting is required, but in this case it doesn't seem necessary. You can try this build and see if it fixes the issue:
https://github.com/univrsal/input-overlay/actions/runs/5662116489 (builds are at the bottom)

**Comment by xoxfaby** [comment] 2023-07-26 07:05
On a quick test, this has completely solved the problem for me. I will let it run for a while to see if the lack of rehooking means it breaks eventually, but on a first test, with this build I don't see any missed inputs.

**Comment by kwhat** [comment] 2023-07-26 17:25
I will likely pull out the code in question or seriously rework it in the 1.3 branch.

**Comment by univrsal** [comment] 2023-07-26 17:33
Thanks for your input, I guess I'll just use the "fix" I have for now.

**Comment by univrsal** [comment] 2023-09-04 15:44
I have merged the "fix" into master for now, we'll see if it causes any further issues.

**Closed by univrsal** 2023-09-04 15:44 UTC
