### ISSUE TITLE
Incorrect texture offsets in Linux release

### ISSUE THREAD

**Issue by zapakh** [univrsal/input-overlay#62] opened 2018-11-07 21:24 UTC
I downloaded the input-overlay.v4.7.4b.zip release and installed the Linux plugin.  The functionality is fine but the keyboard overlay looks like this:

![input-overlay-bug](https://user-images.githubusercontent.com/3113256/48161685-28ffc000-e2a9-11e8-893d-9a9f42132f8e.png)

The date of the unzipped bin/64bit/input-overlay.so file is Febuary 16.  Is it just that the Linux plugin needs to be recompiled?

**Comment by univrsal** [comment] 2018-11-08 12:10
Yeah I didn't compile the binaries for linux for a while.
The problem is that I'm not sure whether the 4.7 version will actually compile on linux anymore. I have spend the past months only working on version 5.
You can try compiling it though and if you have any issues let me now. I can also alternatively provide you with a version 5 build, but it's built on Arch, which means it might not work on your setup.

**Comment by univrsal** [comment] 2018-12-10 12:20
I'll just close this for now

**Closed by univrsal** 2018-12-10 12:20 UTC

**Comment by Lightsockie** [comment] 2019-01-15 02:33
Hey, getting the same problem as OP. Can I have aforementioned build? 

Also, I get this when I try to compile:
```
cmake . 
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at io-obs/CMakeLists.txt:123 (install_obs_plugin_with_data):
  Unknown CMake command "install_obs_plugin_with_data".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

```

**Comment by univrsal** [comment] 2019-01-15 09:51
the obs plugin is intended to be built alongside obs-studio, so you'd have to first clone obs-studio and then clone this repository into the plugins folder. I'll try and build version 5 and upload the build here.

**Comment by univrsal** [comment] 2019-01-18 10:47
Did you load the version 5 presets? They're in this repository under the presets folder. The old presets don't work with the new version

**Comment by Lightsockie** [comment] 2019-01-20 03:39
Ah, I didn't know there was new presets. Loading up those ones fixes the issue. Sorry, I thought it was known not working. It's working in this 5.0 build with the new presets though. Thanks!
