### ISSUE TITLE
right button press rendered as wheel click on linux

### ISSUE THREAD

**Issue by janSopi303** [univrsal/input-overlay#262] opened 2022-07-24 17:08 UTC
**Describe the bug**
on my linux version right clicks are rendered as button 3 while wheel clicks are button 2. it's easy to change the right clicks to be button 3, however I find myself unable to change the keycode for the wheel click

**To Reproduce**
Ig just have the wheel mapped as button 2

**Expected behavior**
this is thecnically the expected behaviour in my system, however it is not normal to not be able to change this in the json file

**Screenshots**
here's a screenshot of what I'd like the code to be able to do (which doesn't work)
![Selection_006](https://user-images.githubusercontent.com/109916554/180658382-bcd28d73-5ebf-4f87-8a7c-e44b9615df83.png)

**Comment by adnub** [comment] 2022-08-09 21:22
Having the same issue here. Would very much like to be able to change the keybind of the mousewheel click too.

As a workaround for now I've edited the PNG file so it doesn't show the mousewheel as clicked when I click my RMB. Though of course it also won't show when I actually use the mousewheel button. I barely use it in games anyway, so it's not too bad for me.

**Comment by univrsal** [comment] 2022-08-29 09:10
Duplicate of #180

**Closed by univrsal** 2022-08-29 09:10 UTC
