### ISSUE TITLE
Ubuntu 18.04 - Minimal history

### ISSUE THREAD

**Issue by mazunki** [univrsal/input-overlay#75] opened 2019-04-06 16:17 UTC
**Describe the bug**
Trying to add minimal-history images to a layer crashes the program. Running from terminal I get a segmentation fault, with and without sudo.

**To Reproduce**
Download https://github.com/univrsal/input-overlay/releases v4.7.4b, and install by the following instructions for Linux:
```
1. Download the latest release zip
2. Create a folder called "input-overlay" in "/usr/share/obs/obs-plugins"
3. Copy the contents of the folder "data" in "plugin-linux" into the new folder
4. Copy the file "input-overlay.so" in "bin/64bit" into "/usr/lib/obs-plugins"
5. Install libuihook over your package manager or (only try this if compiling is not an option) download this binary and copy it into "/usr/lib" (and "usr/lib64" if necessary)
```
from https://obsproject.com/forum/resources/input-overlay.552/

Unzip minimal-history zipfile, and select any of the .png desgins as your key icon texture, and once you select minimal.ini as your key icon config, OBS will automatically close after crashing.

**Expected behavior**
A visible icon instead of plain text per keypress in the history layer.

**Screenshots**
![image](https://user-images.githubusercontent.com/32819373/55672120-88cdb780-5897-11e9-8e13-639520a2053d.png)
![image](https://user-images.githubusercontent.com/32819373/55672122-8d926b80-5897-11e9-88c2-9ed77fa0431b.png)

**Additional information:**
- v.4.7.4b
```bash
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
info: CPU Speed: 4200.035MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 48231MB Total, 34313MB Free
info: Kernel Version: Linux 4.18.0-17-generic
info: Distribution: "Ubuntu" "18.04"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.1
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 23.0.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX TITAN X/PCIe/SSE2
info: OpenGL loaded successfully, version 3.2.0 NVIDIA 418.56, shading language 1.50 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
info: NVENC supported
info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     libobs-linuxbrowser.so
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.usb-Astro_Gaming_Inc._ASTRO_MixAmp_Pro-00.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
info: pulse-input: Started recording from 'alsa_input.usb-046d_0825_608AAED0-02.analog-mono'
[swscaler @ 0x557e3acef5a0] deprecated pixel format used, make sure you did set range correctly
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 640x480
info: v4l2-input: Pixelformat: VYUY
info: v4l2-input: Linesize: 1280 Bytes
info: v4l2-input: Framerate: 30,00 fps
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: ~/gits/pyrand/Instant-Lyrics/spotify_lyrics.py (Instant-Lyrics) - Sublime Text (UNREGISTERED)
	class: sublime_text
	Has alpha: no
	Found proper GLXFBConfig: yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite) 2'] update settings:
	title: git manager
	class: xfce4-terminal
	Has alpha: yes
	Found proper GLXFBConfig: yes

info: xshm-input: Geometry 1920x1080 @ 0,0
info: Switched to scene 'Bash'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'AFK':
info:     - source: 'Image' (image_source)
info:     - source: 'Text (FreeType 2)' (text_ft2_source)
info: - scene 'Sublime + bash':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info:     - source: 'Text (FreeType 2) 2' (text_ft2_source)
info:     - source: 'Window Capture (Xcomposite) 2' (xcomposite_input)
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: - scene 'Bash':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info:     - source: 'Window Capture (Xcomposite) 2' (xcomposite_input)
info:     - source: 'Linux Browser' (linuxbrowser-source)
info:     - source: 'Input History' (input-history)
info: - scene 'Scene 2':
info:     - source: 'Monitor 1 (center)' (xshm_input)
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds (source: Mic/Aux)

[0406/180914.917763:INFO:CONSOLE(1)] "Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools", source: https://streamlabs.com/mixed/assets/external/js/external.js?id=42c649783869666efa96 (1)
[0406/180915.260195:INFO:CONSOLE(1)] "Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools", source: https://streamlabs.com/mixed/assets/external/js/external.js?id=42c649783869666efa96 (1)
info: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Desktop Audio)

Gtk-Message: 18:09:18.021: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 18:09:49.865: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 18:11:47.952: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (core dumped)
```

**Additional context**
I installed libuiohook by copying ztaqlp.zip's libuiohook.so.0 file into /usr/lib and into /usr/lib64, after installing its dependencies, according to https://github.com/wilix-team/iohook/tree/master/libuiohook, with
![image](https://user-images.githubusercontent.com/32819373/55672162-042f6900-5898-11e9-8fef-9817d64724bb.png)
`autotools` wasn't found, though.

**Comment by mazunki** [comment] 2019-04-06 16:30
I installed autotools along autoconf with `sudo apt install autotools-dev autoconf`, but the issue still remains.

**Comment by univrsal** [comment] 2019-04-06 17:16
The dependencies are only needed if you try to compile it (Also the repository you linked isn't the official one, [this](https://github.com/kwhat/libuiohook) is).
Since obs is starting and the plugin is loaded there doesn't seem to be an issue with dependencies, but rather with the plugin.

I'll take a look at it though

**Comment by mazunki** [comment] 2019-04-06 17:54
I tried to manually compile it earlier, and tried now with the official link you provided. Running ./bootstrap gives the following error message:
```
./bootstrap.sh: 3: [: Linux: unexpected operator
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory config
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:76: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:99: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

The first [ syntax error was fixed by running with `bash bootstrap.sh` or `source bootstrap.sh`, but the rest of the error message remains. It confuses me that it mentions WIN32, though, on a Linux distro.

**Comment by univrsal** [comment] 2019-04-06 18:14
Which branch did you clone? The master one might not work, 1.1 should compile though

**Comment by mazunki** [comment] 2019-04-06 18:47
Branch 1.1 on Ubuntu LTS 18.04
![image](https://user-images.githubusercontent.com/32819373/55673807-2c759280-58ad-11e9-9f20-4ce6181ab6df.png)

**Comment by univrsal** [comment] 2019-04-06 20:36
I haven't compiled it on ubuntu so I don't really know how to help you with this issue. Some say it's missing packages, but you already installed libtool and autoconf.
I might be able to install ubuntu and see if I can find a fix, though

**Comment by univrsal** [comment] 2019-04-07 19:05
Okay so installed ubuntu 18.04 and didn't run into any issues. These are the packages I installed before running ```./bootstrap.sh```:
```
sudo apt install libx11-dev xutils-dev x11-common dh-autoreconf autotools-dev libtool gcc pkg-config libxtst-dev libxt-dev libxinerama-dev libx11-xcb-dev libxkbcommon-x11-dev libxkbfile-dev
```
I also didn't have to run bootstrap with the bash command. Maybe you're missing a package or adding bash caused the issue, but I couldn't reproduce the error

**Comment by univrsal** [comment] 2019-08-25 23:38
Just tested minimal history on linux and didn't have any issues. I'll close this for now, so just get back to me if you still need help

**Closed by univrsal** 2019-08-25 23:38 UTC
