### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by crazyzimuki** [univrsal/input-overlay#222] opened 2022-02-08 23:05 UTC
I used the overlay creator tool.
Arrow keys register in the browser window, but not in OBS.
Other keys work correctly.
I tried changing the key codes for the arrow keys in notepad.
Couldn't find the keycodes that correctly correspond to the arrow keys.

**Comment by univrsal** [comment] 2022-02-08 23:23
duplicate of #174

**Closed by univrsal** 2022-02-08 23:23 UTC
