### ISSUE TITLE
Display only shortcuts with modifier keys

### ISSUE THREAD

**Issue by nbourre** [univrsal/input-overlay#106] opened 2020-04-03 15:04 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use your plugin when I do programming screencast for my students. Unfortunately, everything that I type on the keyboard shows up.

**Describe the solution you'd like**
Give an option to show only keyboard shortcuts which are mostly used with modifier keys.

**Describe alternatives you've considered**
None found that work with OBS. I've tried Carnac, but it does not show in OBS.

**Additional context**
Can't give any for now.

**Comment by univrsal** [comment] 2020-04-03 22:09
So this would filter out anything that doesn't include ctrl, alt, shift or the windows key? The function keys should probably still be included though since they're frequently used as binds

**Comment by nbourre** [comment] 2020-04-03 22:20
I just wrote this suggestion over my head, I forgot to think about the F-keys.On Fri, Apr 3, 2020 at 18:09 Alex <notifications@github.com> wrote:
So this would filter out anything that doesn't include ctrl, alt, shift or the windows key? The function keys should probably still be included though since they're frequently used as binds

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by delasteve** [comment] 2020-09-17 06:53
I would definitely love to see this as well for the same reasons. Function keys would be beneficial to show as well. Maybe a toggle between all keys, only modifiers, only modifiers and fn keys? I haven't worked in C++ in years, so I don't know how much help I would be, but would be willing to help. If there's something I can do, please let me know.

Carnac works well if you have OBS display a window capture, but doesn't show if you try to window capture. I have sensitive client data I would prefer not to show on stream.

This plugin is pretty slick. Keep up the awesome work.

**Comment by univrsal** [comment] 2021-05-08 11:50
I don't remember if this was requested for the input-overlay source or input-history. If it's the former then it's a duplicate of #73 if it's the latter, input history has been removed and replaced by the ability to host input events on a local WebSocket Server, so people can now create their own overlays or input history visualizations with the browser source.

I don't have the time or experience with CSS and JS to create any for now, but there is an example html file [here](https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/example.html) so if anybody wants to look into creating an overlay that supports this in an input-history style, feel free to use this as a starting point

**Closed by univrsal** 2021-05-08 11:50 UTC
