### ISSUE TITLE
stupid arrow

### ISSUE THREAD

**Issue by Nikodem840** [univrsal/input-overlay#352] opened 2023-06-25 09:01 UTC
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**
the arrow in the mouse doesnt go right direction bruh

**To Reproduce**
get a input overlay
set to mouse with arrow
go to minecraft
be happy with the arrow not pointing correct way you are moving the mouse

**Expected behavior**
work.

**Additional information:**
- 5.0.4

i sent minecraft short video so you can see the mouse pointing DOWN somehow instead of where it should

https://github.com/univrsal/input-overlay/assets/73533218/91968faa-7530-4c52-8613-3e38275bab48

also it never wants to point up no matter what

**Comment by univrsal** [comment] 2023-06-25 12:13
duplicate of #351

**Closed by univrsal** 2023-06-25 12:13 UTC
