### ISSUE TITLE
Input overlay isn't registering my inputs

### ISSUE THREAD

**Issue by RKProgram** [univrsal/input-overlay#284] opened 2022-09-12 05:05 UTC
**Describe the bug**
Input overlay isn't registering my inputs

**To Reproduce**
Steps to reproduce the behavior: Self-explanatory

**Expected behavior**
When I make inputs, it doesn't register my inputs, shown by that it isn't displaying them.

**Additional information:**
- v5.0.0
- https://obsproject.com/logs/Y7mRbP0Qv0SxU40j
- I have tried running OBS Studio as adminstrator, but to no avail.

**Comment by univrsal** [comment] 2022-09-12 07:06
Duplicate of #160

**Closed by univrsal** 2022-09-12 07:06 UTC
