### ISSUE TITLE
Right mouse and middle mouse are swapped on linux

### ISSUE THREAD

**Issue by Sprixitite** [univrsal/input-overlay#300] opened 2022-12-22 19:06 UTC
**Describe the bug**
When using configs generated by the CCT or when using the provided presets, the middle mouse and right mouse buttons are swapped with one another

**To Reproduce**
Steps to reproduce the behavior: Load any of the provided presets or another config generated by the CCT into OBS on linux

**Expected behavior**
Right mouse button is bound to right mouse button, and vice versa

**Screenshots**
- N/A

**Additional information:**
- Plugin version: 5.0 prerelease (I need to use OBS 27 due to nvfbc being incompatible with 28 and above)
- There is no relevant OBS log, as this is a logic error

**Additional context**
This is caused because the CCT and provided presets assume the use of windows (on which left mouse is keycode 1, right mouse is keycode 2, middle mouse is keycode 3), however on linux using xorg (and potentially wayland, I am unsure as to this however) the middle mouse is keycode 2, and the right mouse is keycode 3

**Comment by univrsal** [comment] 2022-12-23 11:59
Duplicate of #180

**Closed by univrsal** 2022-12-23 11:59 UTC
