### ISSUE TITLE
Input History Missing

### ISSUE THREAD

**Issue by jcdied4me** [univrsal/input-overlay#194] opened 2021-07-25 22:01 UTC
I just learned about input overlay and input history. I am very interested in input history for when I teach software but input overlay when I play games. Is there a reason why input history is not available in the latest 5.0 release? And, how can I get it?

**Comment by rafaelsouzams** [comment] 2021-07-26 03:30
same here!!!

**Comment by univrsal** [comment] 2021-07-26 11:49
Input history was removed and replaced with the option to visualize inputs over the browser source which is better in every way except that there's not presets for it right now and creating them requires some knowledge of CSS, HTML and JavaScript. I have not had the time to create a preset that mimics the old input history behaviour.

**Comment by jcdied4me** [comment] 2021-07-26 17:49
Is there a plan to implement a preset for this anytime soon? Kind of
important for those of us creating tutorials for software, not games.
Having the whole keyboard displayed is nice and all, but it takes up way
too much space on the screen for my purposes.

Also, are there any default presets for versions that had “input history”
using images? The new school year is about to start and I need to begin
recording lessons asap. This feature would be very helpful (key images).

Thanks for the help.

**Comment by rufusdufus0** [comment] 2021-07-26 18:26
I was having the same issue while trying to use Input History for a university assignment and just installed an older version, since I'm not too code savvy and don't care for any of the new 5.0 functionality.

[https://github.com/univrsal/input-overlay/releases](url)

**Comment by jcdied4me** [comment] 2021-07-26 18:31
I have the previous version installed already. I’m looking for a config
file and icon file to use with key images. The text is not helpful in this
circumstance, especially because it captures every input rather than only
shortcuts.

**Comment by rafaelsouzams** [comment] 2021-07-28 17:16
I also tried the old version. The keys appear in text mode, but I would like to use in Icon mode, and in this mode it's not working!
![image](https://user-images.githubusercontent.com/25182245/127367169-1e7d2590-51b7-4827-93c8-472a81039c69.png)
![image](https://user-images.githubusercontent.com/25182245/127367194-854382a4-4f7f-4d6a-b54e-1bc6a10e759e.png)

**Comment by univrsal** [comment] 2021-07-28 22:13
Well you need a preset for the icon mode to work. There's an example one for the arrow keys.

**Comment by GitHubGoody** [comment] 2022-02-27 13:37
@univrsal 

Hello. Has there been any progress on this or is there a guide on how to configure the [arrows example](https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/example.html) to understand what needs to be modified to get it to work for more use cases?

**Comment by univrsal** [comment] 2022-02-27 13:40
https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/input-history-windows-keyboard.html
Is basically input history

**Comment by GitHubGoody** [comment] 2022-02-28 18:15
@univrsal Thank you. I'm sorry if I'm being dense here, but how do I put that into this?
![image](https://user-images.githubusercontent.com/46235745/156036123-9195cf6c-44d8-454c-8f1f-d2aea4e06456.png)

**Comment by univrsal** [comment] 2022-02-28 19:40
It's an html file, you load it in a browser source

**Comment by GitHubGoody** [comment] 2022-03-01 20:17
Ah. I didn't know Input Overlay had a settings dialog. LOL.

Alright, I just saved the contents of your link above into Notepad++ and saved as an .html. I was able to configure the Browser source and it's working, but OBS keeps crashing now.

It was stable before enabling the web socket server. Any idea why it might be crashing now?

Also, how can I configure it to only show certain key modifier key presses (i.e. Ctrl, Alt, Shift)?

![image](https://user-images.githubusercontent.com/46235745/156242270-f8e347eb-9b2e-410c-9ac2-9ee925985c4f.png)

**Comment by univrsal** [comment] 2022-03-01 22:49
No, do you have a crash log? You'd have to edit the html file to filter keys

**Comment by GitHubGoody** [comment] 2022-03-02 16:14
Here are the three from yesterday and three from today:
[Crash 2022-03-01 15-02-57.txt](https://github.com/univrsal/input-overlay/files/8170169/Crash.2022-03-01.15-02-57.txt)
[Crash 2022-03-01 15-05-04.txt](https://github.com/univrsal/input-overlay/files/8170171/Crash.2022-03-01.15-05-04.txt)
[Crash 2022-03-01 15-08-26.txt](https://github.com/univrsal/input-overlay/files/8170172/Crash.2022-03-01.15-08-26.txt)
[Crash 2022-03-02 09-33-24.txt](https://github.com/univrsal/input-overlay/files/8171084/Crash.2022-03-02.09-33-24.txt)
[Crash 2022-03-02 11-00-46.txt](https://github.com/univrsal/input-overlay/files/8171087/Crash.2022-03-02.11-00-46.txt)
[Crash 2022-03-02 11-04-11.txt](https://github.com/univrsal/input-overlay/files/8171088/Crash.2022-03-02.11-04-11.txt)

I started to look into customizing the html. I cannot figure out where something as simple as "text-align: center" needs to go. I put it in the body and span.key elements of the .html as well as the Custom CSS section of the Source. It doesn't center the text.

I figure I should get a handle of editing the look before I try to mess with the function (custom keys, etc.).

**Comment by univrsal** [comment] 2022-03-02 19:13
@christiankyle-ching made the html/css so you're probably better off asking him

**Comment by christiankyle-ching** [comment] 2022-03-02 23:30
> Alright, I just saved the contents of your link above into Notepad++ and saved as an .html. I was able to configure the Browser source and it's working, but OBS keeps crashing now.
> 
> It was stable before enabling the web socket server. Any idea why it might be crashing now?

I also experienced OBS crashing, but I think it's related to OBS handling browser sources in general, as opposed to specifically this plugin. See the latest release. From the crash logs, I assume you're still in 27.2.1.

> https://github.com/obsproject/obs-studio/releases/tag/27.2.2
> > Fixed an issue that triggered a full system freeze for some users. Made a legendary workaround to some sort of driver/kernel bug which was triggered by the browser source (I am really proud of this) [Jim]

---

> Also, how can I configure it to only show certain key modifier key presses (i.e. Ctrl, Alt, Shift)?

You just have to comment out certain keys in the dictionary `var KEYCODES = ...`

https://github.com/univrsal/input-overlay/blob/1fb2ec95fbd3041bf006f20054b0c58400b459f5/projects/plugin/data/input-history-windows-keyboard.html#L311-L318

---

> I started to look into customizing the html. I cannot figure out where something as simple as "text-align: center" needs to go. I put it in the body and span.key elements of the .html as well as the Custom CSS section of the Source. It doesn't center the text.

I'll try and update it to handle `text-align`. That's not something I did not consider when making the template, as I intended only to have a minimal working example.

**Comment by univrsal** [comment] 2022-03-02 23:34
The crashes linked here are caused by input-overlay, but they all seem to happen on exit.

**Comment by christiankyle-ching** [comment] 2022-03-02 23:45
> The crashes linked here are caused by input-overlay, but they all seem to happen on exit.

I see. Though I noticed that the crashes are lessened after updating to 27.2.2, but it's still occurring (just crashed right now lol).

**Comment by univrsal** [comment] 2022-03-02 23:50
Does it happen on exit? If not can you upload the crash?

**Comment by christiankyle-ching** [comment] 2022-03-03 00:26
[Crash 2022-03-03 08-23-32.txt](https://github.com/univrsal/input-overlay/files/8173794/Crash.2022-03-03.08-23-32.txt)

It happened once when I was using `Alt + Tab`, but sometimes crashes randomly. Still cannot exactly pinpoint the cause of the issue.

**Comment by univrsal** [comment] 2022-03-03 00:31
that looks similar to the ones linked further up. It crashes when sending data over the websocket.

**Comment by GitHubGoody** [comment] 2022-03-03 19:11
@univrsal Here are two more crash logs that were basically back-to-back. I was trying to edit scene collections at the time. I'm now on v27.2.3.

[Crash 2022-03-03 13-47-42.txt](https://github.com/univrsal/input-overlay/files/8180391/Crash.2022-03-03.13-47-42.txt)
[Crash 2022-03-03 13-48-17.txt](https://github.com/univrsal/input-overlay/files/8180392/Crash.2022-03-03.13-48-17.txt)

Here's another one while I was typing this with OBS running in the background...
[Crash 2022-03-03 14-03-49.txt](https://github.com/univrsal/input-overlay/files/8180405/Crash.2022-03-03.14-03-49.txt)

...and another one as I closed OBS...
[Crash 2022-03-03 14-08-52.txt](https://github.com/univrsal/input-overlay/files/8180435/Crash.2022-03-03.14-08-52.txt)


@christiankyle-ching Thank you for making those changes so quickly! Centering text is working well for me.

Some (hopefully) quick questions for you:
- Is the intent to modify the look via the Custom CSS settings of the Brower source, the .html, or both?
- How/where would I set single line spacing (defaults to double)?
- Can I pull in key graphics in place of the text (i.e. only the pressed keys would still show, but graphically)?
- How/where can I set a timeout for the screen text so that it disappears after X seconds?

**Comment by univrsal** [comment] 2022-03-03 22:15
The first and last crash are not related to input overlay as far as I can tell, the other ones are the same cause as before.

**Comment by christiankyle-ching** [comment] 2022-03-04 00:22
> * Is the intent to modify the look via the Custom CSS settings of the Brower source, the .html, or both?

For simple modification such as font-size, font-family, text-align, and color, use the Custom CSS. For more specific customization, you have to edit the HTML.

> * How/where would I set single line spacing (defaults to double)?

Adjust the margins and padding inside the `<style>` tag. I placed some comments there to indicate the spacing between key combinations, and when a line is wrapped (greater than window width of the browser source).

> * Can I pull in key graphics in place of the text (i.e. only the pressed keys would still show, but graphically)?

You mean icons instead of text? If so, then you just have to add an `<svg>` of your choice, assign it an `id` (preferably follow the naming convention I used, "SVG_KEYCODENAME"), then copy the keycode (0x----) from the `KEYCODES` of the key you want to replace with icon. Add that to the `KEYICONS` variable, where the value is the `<svg>` element that you can get using the `id` you assigned it earlier.

I assume this is to replace all the letters and characters for styling. If it is, then I think it's much  better to change the font family first by installing a font to your system, then changing the font-family in CSS. Manually adding SVG graphics to each key in the keyboard would be difficult (at least for my template).

> * How/where can I set a timeout for the screen text so that it disappears after X seconds?

As of now, there's no functionality for that. I might try and implement it. As I said earlier, this was supposed to be a minimally working example 😂

**Comment by christiankyle-ching** [comment] 2022-03-04 04:15
@univrsal, @GitHubGoody 

I did not experience crashes when I have OBS minimized, without a Browser Source, and websocket forwarding enabled. It crashed when I switched back to OBS though. Don't know if that will help. Unfortunately, I can't help debugging this crash issue as I am not familiar with C or C++.

It might also be a good idea to make a separate issue about the crashes. This issue could be more focused on input-history templates as a feature request.

---

I am also working on improving the template and adding features such as the timeout feature. I also intend to provide a README for using the template itself (might just include it in the next PR).

I see the new approach of using Browser Source + websocket more flexible, but has higher learning curve especially for those unfamiliar with basic HTML, CSS, and JS.

---
### Custom CSS customization

![image](https://user-images.githubusercontent.com/57316283/156698031-c133a912-000b-45b8-9ca4-e82a44a8237f.png)

### Fade after delay

https://user-images.githubusercontent.com/57316283/156698137-ba1e7f83-5450-43bb-b0c8-6f1ac758a936.mp4

**Comment by christiankyle-ching** [comment] 2022-03-04 04:26
Crash without pressing any keys, just editing the Browser Source.
[Crash 2022-03-04 12-24-42.txt](https://github.com/univrsal/input-overlay/files/8183050/Crash.2022-03-04.12-24-42.txt)

**Comment by univrsal** [comment] 2022-03-04 13:49
> It might also be a good idea to make a separate issue about the crashes. This issue could be more focused on input-history templates as a feature request.

I've mentioned them in #230

 > I also intend to provide a README for using the template itself. If you want this README for customizing my template, where should I put these files? I really think having a folder for each input-history template would be beneficial. This way, resources for the template (README, images, etc) can be separated. I just don't know where should I place this folder in the project structure.

Yeah, the data folder of the plugin was kind of a bad pick. I just put it there so it gets bundled with the plugin. It would probably be best to put all input history presets in [projects/presets](https://github.com/univrsal/input-overlay/tree/master/projects/presets) as a separate folder with a README and additional files. 

> I see the new approach of using Browser Source + websocket more flexible, but has higher learning curve especially for those unfamiliar with basic HTML, CSS, and JS.

True, but with the basic history preset available it's already better than the old input history source. I guess we could add a way for users to configure some basic settings which get sent over the WebSocket when the connection is opened, but that makes things a little more complicated.

**Comment by GitHubGoody** [comment] 2022-03-04 18:22
@christiankyle-ching,

> 
> I am also working on improving the template and adding features such as the timeout feature.
> 
> I also intend to provide a README for using the template itself. If you want this README for customizing my template, where should I put these files? I really think having a folder for each input-history template would be beneficial. This way, resources for the template (README, images, etc) can be separated. **I just don't know where should I place this folder in the project structure.**
> 
Thank you!
> I see the new approach of using Browser Source + websocket more flexible, but has higher learning curve especially for those unfamiliar with basic HTML, CSS, and JS.
> 
I resemble that remark! ;-)
> ### Custom CSS customization
> ![image](https://user-images.githubusercontent.com/57316283/156698031-c133a912-000b-45b8-9ca4-e82a44a8237f.png)
> 
That looks really good actually. If I could customize a few more things, I don't think I'd need to use icons

With this...
body { background-color: gray; margin: 0px auto; overflow: hidden; color: white; background: none; text-align: center; }

I'm getting this...
![image](https://user-images.githubusercontent.com/46235745/156819655-79e3e3ea-f5d6-4a54-8a76-c46c641477ce.png)

> ### Fade after delay
>  sample-fading.mp4
Sweet! Getting close to a pull request on that?

**Comment by christiankyle-ching** [comment] 2022-03-05 06:48
> With this... body { background-color: gray; margin: 0px auto; overflow: hidden; color: white; background: none; text-align: center; }
> 
> I'm getting this... ![image](https://user-images.githubusercontent.com/46235745/156819655-79e3e3ea-f5d6-4a54-8a76-c46c641477ce.png)
>
> But, I cannot get the rounded rectangle fill to turn gray. Also, I'd like to add an outline (stroke of sorts) to the rounded rectangle. Is that possible?

You're setting the background of the `body` element (the whole page) twice. The rounded rectangle's CSS class is `.key`. So to modify it, you should modify like so: 
```css
.key { background-color: gray; }
```

The background of the body should be transparent, hence the default value (`body { background-color: rgba(0, 0, 0, 0); }`).

For the stroke, you'll use the `border` styling in CSS.

I'll soon upload a proper README to hopefully guide beginners in modifying the template.

**Comment by christiankyle-ching** [comment] 2022-03-07 04:03
@univrsal We can update the wiki to point out the [new location of the preset with README](https://github.com/univrsal/input-overlay/tree/master/projects/presets/input-history-windows).

@GitHubGoody If you still have any questions or feature requests in the template, feel free to share it here 🙂

**Comment by univrsal** [comment] 2022-03-07 13:29
Done. I think we can basically closes this issue now. I'll try and fix inputs on linux at some point, but for now this is good enough. Thanks again for taking the time to implement this.

**Closed by univrsal** 2022-03-07 13:29 UTC

**Comment by GitHubGoody** [comment] 2022-03-07 18:57
@christiankyle-ching Awesome! I've got it configured for the look and function I was after and it's all in the the .html. Thank you!

@univrsal, Thank you too for this plug-in. I'll add my latest crash reports to https://github.com/univrsal/input-overlay/issues/230.

**Comment by christiankyle-ching** [comment] 2022-03-08 01:31
> The last bit of functionality I'm hoping to get would be an option to enable/disable keys UNLESS a modifier is pressed in combination (e.g., pressing "G" would not display, but pressing "ALT + G" would display). I imagine that would be a pretty easy javascript change, and I could eventually figure it out, but figured I'd ask you first since that may be something others would also like to have.

@GitHubGoody I can do that in the future but can you give an example scenario on when would that be useful?

**Comment by GitHubGoody** [comment] 2022-03-08 01:48
> @GitHubGoody I can do that in the future but can you give an example scenario on when would that be useful?

Thanks. Any scenario where the user is demonstrating something which requires the use of hot keys that use modifiers and needs to type in a text field as part of that tutorial. I wouldn't do this, but imagine I wanted to demonstrate how to input a comment on GitHub. I may want to demo how to bold (Ctrl-B), but not every letter I type while typing a bolded demo comment...maybe not the best example, but good enough? 😆

**Comment by lazuee** [comment] 2022-06-25 03:33
Hello, can some tell me how to use input history? the websocket server doesn't seem to be working...

**Comment by AltamiroAJ** [comment] 2024-03-03 21:21
I see we got the new input history on the last release.

Can we have an option to combine words ? Maybe with a delay or an specific keypress, I want to record Rhinoceros3D videos and have the overlay show the typed command I am using :)

I tried doing it myself with help of chatGPT but I am that bad at coding HTML
